### PR TITLE
Liveries from the Flightgear Livery database added

### PR DESCRIPTION
**Pull request by IAHM-COL**
http://liveries.flightgear.org/aircraft.php?id=37
Authors (Thanks to)
    Lukas Miersch
    Erick Cerqueira
    Jon E.
    Christian Heinrich
    Martien van der P.
    Felix Nordmark
    Nick Reimer

### CODE REVIEW

**Comment by dogsaysmoo** [comment]
Only 2 of the liveries in the database work with the fg3.0+ version of the 757, so I'm not going to merge this.

**Comment by dogsaysmoo** [comment]
Only 2 of the liveries in the database work with the fg3.0+ version of the 757, so I'm not going to merge this.

**Comment by IAHM-COL** [comment]
Thanks John
Do you know which ones specifically, and do you know whether these are already installed?

Best,
IH-COL

**Comment by dogsaysmoo** [comment]
Thomas Cook Egypt livery and USAF. They are not included as of now.

**Comment by IAHM-COL** [comment]
ok. I reverted the previous unnecessary (incorrectly mapped liveries) will add these two only 
Thanks a lot for the revision

A similar case occurrs over the B707, where several of the liveries on the database are legacy and of no good use anymore :S

**Comment by dogsaysmoo** [comment]
I think the b1900 may have the same issue.

**Comment by IAHM-COL** [comment]
will look into that case, as well.
Many of the liveries on the database had issues of several variable nature :cry: 

Some brought undesirable files to the aircraft trees, and I had to clean those
Other the xml was incorrect, like calling for a texture file that exists with different name
Others placed the files in awkward trees! 

This work of adding the liveries went from luxury to necessity... quite fast

**Comment by IAHM-COL** [comment]
https://github.com/FGMEMBERS/b1900d/commit/0bda6652a5b970574606017a6a318d5d89149c84
Thanks John

I deleting the legacy liveries.
Still several new liveries from the database were still applicable, but a few were now removed.

Thanks again for reporting

**Pull request closed without merging**
